name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Typst
        uses: typst-community/setup-typst@v4
      - name: Compile files
        run: ./compile.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build
